{*******************************************************************************

  Lens - magnifying glass. Include file.

  Author:    KARPOLAN
  E-Mail:    karpolan@ABFsoftware.com, karpolan@i.am
  WEB:       http://www.ABFsoftware.com, http://karpolan.i.am
  Copyright © 1996-2000 by KARPOLAN.
  Copyright © 1999 UtilMind Solutions.
  Copyright © 2000 ABF software, Inc.

*******************************************************************************}

{$I krpRegions.inc}

//==============================================================================
// Directives
//==============================================================================

//------------------------------------------------------------------------------
// Directive DEBUG turn on/off some debug messages.
// {$Define DEBUG}

//------------------------------------------------------------------------------
// Difine Release to build a release of Lens - magnifying glass.
// {$Define Release}

//------------------------------------------------------------------------------
// Difine LocalUpgrade (simple uncomment) for testing upgrading process locally.
// {$Define LocalUpgrade}

